### ISSUE TITLE
kilo syntax

### ISSUE THREAD

**Issue by bj0** [kunalsheth/units-of-measure#8]
In the demo there is code: `val mass = 3.kilo(Gram)`, but When I try to do this, I get the following compile error:

>Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val M /* = L0M1T0I0Theta0N0J0 */.Gram: Double defined in info.kunalsheth.units.generated
public val Number.Gram: M /* = L0M1T0I0Theta0N0J0 */ defined in info.kunalsheth.units.generated

I'm not sure why it can't pick between those 2 extension methods.

same for: 
`val speed = 65.Mile / Hour`

It cannot figure out `Hour`

This is in a unit test in a kotlin/jvm library

**Comment by kunalsheth** [comment]
Do you have both of the following imports?
```kotlin
import info.kunalsheth.units.generated.*
import info.kunalsheth.units.math.*
```

**Comment by bj0** [comment]
I have the first, `math` is unresolved.

**Comment by kunalsheth** [comment]
What version are you using?

**Comment by bj0** [comment]
Ah ok, I was using `3.3.2` which I copied from one of the examples somewhere.

One last question:  If you do something like:
`val velocity = 3.Meter / Second`.  And you have 
```u("Meter"...
u("Mile"...
u("Second"...
u("Hour"...```

To get the velocity value back out as miles/hour, you have to create a separate unit of measure for that, right?  Having hour and mile aren't enough?  If so, is it possible to define it based on already-defined hour and mile?

**Comment by kunalsheth** [comment]
The latest version is `5.2.4`.
To get the value back as `MilesPerHour` you'll need to define a separate unit. _units-of-measure_ is not smart enough to figure out more complicated conversions from `Quantity` to `Double`.

**Comment by kunalsheth** [comment]
As of now, there isn't a clean way to have `MilesPerHour` based off the already existing `Hour` and `Mile`.
You'll have to define an entirely new unit.
