### ISSUE TITLE
uom module fails first build with: Declaration annotated with '@OptionalExpectation' can only be used in common module sources

### ISSUE THREAD

**Issue by bj0** [kunalsheth/units-of-measure#9]
Since converting to a multiproject module, I am getting the following error when trying to build from a clean directory (`./gradlew clean`):

> Declaration annotated with '@OptionalExpectation' can only be used in common module sources

I believe this is caused by the `@JsName` annotations.  

It only happens on the first invocation of `./gradlew build`, if I re-run `./gradlew build` a second time everything compiles and runs fine. 

This isn't a problem for development/testing on my workstation, but it is a problem for an automated build server.  Have you seen this issue or have any ideas?  

My module's `build.gradle` is:
```
apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'info.kunalsheth.units.gradle'

repositories.mavenCentral()

kotlin {
    jvm()

    sourceSets {
        commonMain {
            kotlin.srcDirs += generateUnitsOfMeasure.generatedSrcDir
            dependencies { implementation kotlin('stdlib-common') }
        }
        jvmMain {
            dependsOn commonMain
            dependencies {
                implementation kotlin('stdlib')
            }
        }
        jvmTest {
            dependencies {
                implementation kotlin('test')
                implementation kotlin('test-junit')
                implementation "com.google.truth:truth:0.45"
            }
        }
        all {
            languageSettings.enableLanguageFeature('InlineClasses')
        }
    }
    targets.all {
        compilations.all { compileKotlinTask.dependsOn(generateUnitsOfMeasure) }
    }
}

// workaround for https://youtrack.jetbrains.com/issue/KT-27170
configurations {
    compileClasspath
}

apply from: 'units-of-measure.gradle'

```

**Comment by kunalsheth** [comment]
Hi Brian, this is unfortunate. I was able to replicate it, but I do think its an issue on Kotlin's end.

Considering how painful the `@JsName` annotations have been, I've decided to remove them from the library. Version 5.3.2 does not ship with the `±` functions anymore. Though the user can still define them manually if they want: https://github.com/kunalsheth/units-of-measure/blob/9c2045c5c72f91f57dfa72a38ac3bfdcf54da5dd/demo/jvm/src/main/kotlin/info/kunalsheth/units/sample/Sample.kt#L54
